apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  labels:
    app: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
      - name: data-generator
        image: fourat98/energy-data-generator:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "user"
        - name: RABBITMQ_PASS
          value: "password"